import type { Location, Service, Testimonial, CaseStudy, BlogPost, PricingPlan } from "@/types";

export const SITE_CONFIG = {
  name: "Muhammad Umair",
  brand: "mumairdigital.com",
  tagline: "Digital Marketing That Fills Your Phone With Leads",
  subTagline: "Local SEO & Digital Marketing Expert for Home Service Businesses in USA & Canada",
  email: "info@mumairdigital.com",
  whatsapp: "+923209943057",
  whatsappNumber: "923209943057",
  linkedIn: "https://linkedin.com/in/mumairdigital",
  experience: "2+",
  clients: "30+",
  projects: "50+",
  successRate: "95%",
  baseUrl: process.env.NEXT_PUBLIC_SITE_URL ?? "https://mumairdigital.com",
};

export const NAV_SERVICES = [
  { label: "Local SEO", href: "/services/local-seo", description: "Rank #1 on Google Maps" },
  { label: "Web Design", href: "/services/web-design", description: "High-converting websites" },
  { label: "Google Ads", href: "/services/google-ads", description: "$2-$5 cost per conversion" },
  { label: "Meta Ads", href: "/services/meta-ads", description: "Facebook & Instagram Ads" },
  { label: "SEO Audit", href: "/services/seo-audit", description: "Full technical analysis" },
  { label: "Google Business Profile", href: "/services/google-business-profile", description: "GBP optimization" },
];

export const NAV_LOCATIONS_USA = [
  { label: "Houston, TX", href: "/locations/houston-tx" },
  { label: "Phoenix, AZ", href: "/locations/phoenix-az" },
  { label: "San Antonio, TX", href: "/locations/san-antonio-tx" },
  { label: "Jacksonville, FL", href: "/locations/jacksonville-fl" },
  { label: "Columbus, OH", href: "/locations/columbus-oh" },
  { label: "Charlotte, NC", href: "/locations/charlotte-nc" },
];

export const NAV_LOCATIONS_CANADA = [
  { label: "Calgary, AB", href: "/locations/calgary-ab" },
  { label: "Edmonton, AB", href: "/locations/edmonton-ab" },
  { label: "Ottawa, ON", href: "/locations/ottawa-on" },
];

export const STATS = [
  { label: "Years Experience", value: 2, suffix: "+" },
  { label: "Happy Clients", value: 30, suffix: "+" },
  { label: "Projects Completed", value: 50, suffix: "+" },
  { label: "Success Rate", value: 95, suffix: "%" },
];

export const SERVICES: Service[] = [
  {
    slug: "local-seo",
    title: "Local SEO",
    shortTitle: "Local SEO",
    icon: "MapPin",
    description: "Dominate local search results and Google Maps for your home service business. Get found by customers actively searching for your services in your city.",
    shortDescription: "Rank higher on Google Maps and local search. Get more calls from people ready to hire.",
    features: [
      "Google Business Profile optimization",
      "Local citation building & cleanup",
      "Review generation & management",
      "Local keyword ranking strategy",
      "NAP consistency across directories",
      "Competitor gap analysis",
    ],
    results: "400+ monthly calls for HVAC client",
    heroTagline: "Rank #1 on Google Maps & Get More Calls",
    process: [
      { step: "01", title: "Local SEO Audit", description: "Complete analysis of your current local presence, GBP, citations, and competitor landscape." },
      { step: "02", title: "Strategy & Optimization", description: "Optimize GBP, build local citations, fix NAP issues, and implement local keyword strategy." },
      { step: "03", title: "Content & Reviews", description: "Create locally-optimized content, generate reviews, and build local authority signals." },
      { step: "04", title: "Monitor & Report", description: "Track rankings, calls, and leads with monthly reports showing clear ROI." },
    ],
    benefits: [
      { title: "More Phone Calls", description: "Appear in the 3-pack and get calls from customers ready to hire now." },
      { title: "Higher Google Maps Ranking", description: "Dominate the map pack in your city and surrounding areas." },
      { title: "Increased Website Traffic", description: "Drive qualified local traffic to your website from organic search." },
      { title: "Better Online Reputation", description: "Build a 5-star reputation that converts visitors into customers." },
    ],
    faq: [
      { q: "How long does Local SEO take?", a: "Most clients see improvements in 60-90 days. Significant results by month 3-4." },
      { q: "Do you guarantee rankings?", a: "I guarantee consistent effort and proven strategies. Rankings improve in competitive markets within 3-6 months." },
    ],
    ctaText: "Get Your Free Local SEO Audit",
  },
  {
    slug: "web-design",
    title: "Web Design",
    shortTitle: "Web Design",
    icon: "Monitor",
    description: "High-converting websites built specifically for home service businesses. Mobile-first, fast-loading, SEO-optimized, and designed to turn visitors into leads.",
    shortDescription: "High-converting websites built for home service businesses. Fast, SEO-friendly, mobile-first.",
    features: [
      "Conversion-first design strategy",
      "Technical SEO built-in",
      "Page speed optimization",
      "Lead capture forms & CTAs",
      "Mobile-first responsive design",
      "Google Analytics & tracking setup",
    ],
    results: "180%+ traffic increase for clients",
    heroTagline: "Websites That Convert Visitors Into Paying Customers",
    process: [
      { step: "01", title: "Discovery & Planning", description: "Understand your business, target market, and competitors to plan the perfect website." },
      { step: "02", title: "Design & Wireframes", description: "Create conversion-focused designs optimized for your specific home service business." },
      { step: "03", title: "Development & SEO", description: "Build fast, secure websites with technical SEO, schema markup, and lead capture forms." },
      { step: "04", title: "Launch & Optimize", description: "Launch, set up analytics, and continuously optimize for better conversion rates." },
    ],
    benefits: [
      { title: "More Leads Online", description: "Websites designed to capture leads, not just showcase your business." },
      { title: "Better First Impressions", description: "Professional design that builds trust and credibility with potential customers." },
      { title: "Faster Page Speed", description: "Optimized for Core Web Vitals and Google Page Speed scores above 90." },
      { title: "Built-in SEO", description: "Technical SEO, schema markup, and optimized content from day one." },
    ],
    faq: [
      { q: "How long does a website take?", a: "Typically 2-4 weeks for a complete home service website with all pages and SEO." },
      { q: "Do you use WordPress?", a: "Yes, I primarily build on WordPress with Elementor or custom themes, depending on your needs." },
    ],
    ctaText: "Get a Free Website Consultation",
  },
  {
    slug: "google-ads",
    title: "Google Ads",
    shortTitle: "Google Ads",
    icon: "Target",
    description: "AI-optimized Google Ads campaigns that deliver $2-$5 cost per conversion for home service businesses. Stop paying $20-$50 per lead with most agencies.",
    shortDescription: "AI-optimized campaigns that deliver $2-$5 cost per conversion for home service businesses.",
    features: [
      "Smart bidding & AI optimization",
      "Call-only campaign setup",
      "Performance Max campaigns",
      "Conversion tracking & analytics",
      "Negative keyword management",
      "A/B testing & landing pages",
    ],
    results: "$2-$5 cost per conversion achieved",
    heroTagline: "$2-$5 Cost Per Conversion — Not $20-$50",
    process: [
      { step: "01", title: "Account Audit & Setup", description: "Review or set up your Google Ads account with proper conversion tracking and goals." },
      { step: "02", title: "Campaign Strategy", description: "Build campaigns targeting high-intent local keywords for your specific service area." },
      { step: "03", title: "Launch & Optimize", description: "Launch campaigns, monitor performance daily, and optimize bids, ads, and targeting." },
      { step: "04", title: "Scale & Report", description: "Scale winning campaigns, pause underperformers, and provide detailed monthly reports." },
    ],
    benefits: [
      { title: "Immediate Lead Flow", description: "Get calls and leads within 24-48 hours of launching campaigns." },
      { title: "Low Cost Per Lead", description: "Consistently achieve $2-$5 cost per conversion vs. industry average of $20-$50." },
      { title: "AI-Powered Optimization", description: "Leverage Google's machine learning with smart bidding strategies for maximum ROI." },
      { title: "Transparent Reporting", description: "See exactly where every dollar goes with detailed conversion tracking." },
    ],
    faq: [
      { q: "What budget do I need?", a: "Most home service businesses start with $500-$1,500/month in ad spend. I recommend starting with $1,000 for optimal results." },
      { q: "How fast will I see results?", a: "Campaigns go live within 48-72 hours. Leads typically start flowing within the first week." },
    ],
    ctaText: "Get a Free Google Ads Audit",
  },
  {
    slug: "meta-ads",
    title: "Meta Ads",
    shortTitle: "Meta Ads",
    icon: "Share2",
    description: "Facebook and Instagram advertising that reaches homeowners in your service area before they even search for your service. Build brand awareness and generate leads.",
    shortDescription: "Facebook & Instagram Ads that reach homeowners in your service area before they search.",
    features: [
      "Facebook & Instagram campaigns",
      "Audience targeting & retargeting",
      "Lead generation forms",
      "Video & image ad creative",
      "Lookalike audience creation",
      "Pixel setup & tracking",
    ],
    results: "3x lead increase for roofing clients",
    heroTagline: "Reach Homeowners Before They Search Google",
    process: [
      { step: "01", title: "Pixel & Tracking Setup", description: "Install Facebook Pixel, set up conversion events, and create custom audiences." },
      { step: "02", title: "Campaign Creation", description: "Build targeted campaigns for your specific home service business and location." },
      { step: "03", title: "Creative & Copy", description: "Create compelling ad creative and copy that resonates with homeowners in your area." },
      { step: "04", title: "Optimize & Scale", description: "Continuously optimize targeting, creative, and bidding for maximum lead volume." },
    ],
    benefits: [
      { title: "Brand Awareness", description: "Get your brand in front of homeowners in your service area before they need your service." },
      { title: "Retargeting Power", description: "Re-engage people who visited your website but didn't call or convert." },
      { title: "Qualified Leads", description: "Target specific demographics, interests, and behaviors that match your ideal customer." },
      { title: "Cost Effective", description: "Often lower cost per lead than Google Ads for certain home services." },
    ],
    faq: [
      { q: "Does Meta Ads work for home services?", a: "Yes, especially for roofing, HVAC replacements, and kitchen/bathroom remodels where buying decisions are planned." },
      { q: "What budget is recommended?", a: "Start with $500-$1,000/month in ad spend. I manage the campaigns for a monthly fee." },
    ],
    ctaText: "Get a Free Meta Ads Strategy",
  },
  {
    slug: "seo-audit",
    title: "SEO Audit",
    shortTitle: "SEO Audit",
    icon: "Search",
    description: "Comprehensive technical and local SEO audit that reveals exactly why your business isn't ranking and provides a clear action plan to fix it.",
    shortDescription: "Full technical and local SEO analysis with clear action plan to fix ranking issues.",
    features: [
      "Technical SEO analysis",
      "Local SEO assessment",
      "Competitor gap analysis",
      "Keyword opportunity report",
      "Google Business Profile audit",
      "Actionable recommendations",
    ],
    results: "Average 47% ranking improvement post-audit",
    heroTagline: "Find Out Exactly Why You're Not Ranking",
    process: [
      { step: "01", title: "Data Collection", description: "Gather data from Google Search Console, Analytics, GBP, and competitor tools." },
      { step: "02", title: "Technical Analysis", description: "Audit site speed, crawlability, mobile optimization, schema markup, and more." },
      { step: "03", title: "Local SEO Review", description: "Analyze GBP, citations, NAP consistency, reviews, and local ranking factors." },
      { step: "04", title: "Action Plan Report", description: "Deliver prioritized recommendations with clear steps to improve your rankings." },
    ],
    benefits: [
      { title: "Clear Action Plan", description: "Know exactly what to fix and in what order for maximum ranking improvement." },
      { title: "Competitor Insights", description: "See what your top competitors are doing right and how to outrank them." },
      { title: "Save Time & Money", description: "Stop guessing and focus your SEO budget on what actually moves the needle." },
      { title: "Expert Analysis", description: "2+ years of home service SEO experience reviewing your specific situation." },
    ],
    faq: [
      { q: "What's included in the audit?", a: "Technical SEO, local SEO, GBP analysis, competitor analysis, keyword gaps, and a prioritized action plan." },
      { q: "How long does it take?", a: "Full audit delivery within 5-7 business days with a video walkthrough of findings." },
    ],
    ctaText: "Order Your SEO Audit",
  },
  {
    slug: "google-business-profile",
    title: "Google Business Profile",
    shortTitle: "GBP Optimization",
    icon: "Star",
    description: "Your Google Business Profile is the #1 local ranking factor. I optimize every element to get you into the 3-pack and drive more calls, directions, and website visits.",
    shortDescription: "GBP optimization that gets you into the Google Maps 3-pack and drives more calls.",
    features: [
      "Complete GBP profile setup & optimization",
      "Category & attribute optimization",
      "Photo & video uploads",
      "Google Posts strategy",
      "Review generation system",
      "Q&A optimization",
    ],
    results: "400+ monthly calls via GBP",
    heroTagline: "Get Into Google Maps Top 3 — Get More Calls",
    process: [
      { step: "01", title: "Profile Audit", description: "Complete audit of your current GBP for missing information, errors, and optimization opportunities." },
      { step: "02", title: "Full Optimization", description: "Optimize every element: categories, services, photos, attributes, and business description." },
      { step: "03", title: "Content Strategy", description: "Implement Google Posts, Q&A responses, and ongoing photo updates." },
      { step: "04", title: "Review Growth", description: "Set up a systematic review generation process to build your 5-star reputation." },
    ],
    benefits: [
      { title: "Map Pack Ranking", description: "Appear in the top 3 on Google Maps for searches in your service area." },
      { title: "More Phone Calls", description: "Drive direct calls from Google Maps without paying for ads." },
      { title: "Better Visibility", description: "Show up when customers search for your exact services in their city." },
      { title: "Trust & Credibility", description: "A complete, optimized profile with reviews builds trust before customers even call." },
    ],
    faq: [
      { q: "Do I need a GBP if I already have a website?", a: "Absolutely. GBP drives more calls than most websites for local businesses. It's the #1 local ranking factor." },
      { q: "How fast can I see GBP improvements?", a: "GBP optimizations can show ranking improvements within 30-60 days. Some clients see results in 2-3 weeks." },
    ],
    ctaText: "Optimize My Google Business Profile",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: "James Mitchell",
    role: "Owner",
    company: "ProFlow Plumbing Services",
    location: "Texas, USA",
    text: "Muhammad's Local SEO work made a huge difference. We went from struggling to get calls to receiving 400+ monthly inquiries. The Google Ads cost per conversion is outstanding at just $2-$5. I highly recommend Muhammad to any home service business looking to grow.",
    result: "400+ Monthly Calls",
    stars: 5,
  },
  {
    name: "Robert Chen",
    role: "Owner",
    company: "AirMax HVAC Solutions",
    location: "California, USA",
    text: "Working with Muhammad on our Local SEO and Google Business Profile has produced incredible results. Our traffic grew 180% and we're now in the top 3 on Google Maps in 3 cities. He knows home service marketing better than anyone we've worked with.",
    result: "180%+ Traffic Growth",
    stars: 5,
  },
  {
    name: "David Thompson",
    role: "Owner",
    company: "QuickFix Roofing Co.",
    location: "Calgary, Canada",
    text: "Muhammad built us a new website and did complete Local SEO. Our leads quadrupled in 5 months. Best investment we made for our roofing business. He's responsive, professional, and delivers real results.",
    result: "4x Lead Increase",
    stars: 5,
  },
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: "proflow-plumbing",
    company: "ProFlow Plumbing Services",
    industry: "Plumbing",
    location: "Texas, USA",
    services: ["Local SEO", "Google Ads"],
    resultHeadline: "400+ Monthly Calls",
    description: "Local SEO and Google Ads for a plumbing company in Texas. Achieved #1 local ranking and $2-$5 cost per conversion on Google Ads within 8 months.",
    duration: "8 Months",
    metrics: [
      { label: "Monthly Calls", value: "400+" },
      { label: "Cost Per Conversion", value: "$2-$5" },
      { label: "Local Rank", value: "#1" },
      { label: "ROI", value: "12x" },
    ],
    badge: "Plumbing",
    badgeColor: "blue",
  },
  {
    id: "airmax-hvac",
    company: "AirMax HVAC Solutions",
    industry: "HVAC",
    location: "California, USA",
    services: ["Local SEO", "Google Business Profile"],
    resultHeadline: "180%+ Traffic Growth",
    description: "Complete Google Business Profile optimization and Local SEO for an HVAC company. Dominated the map pack in 3 cities within 6 months of starting.",
    duration: "6 Months",
    metrics: [
      { label: "Traffic Growth", value: "180%+" },
      { label: "Cities Dominated", value: "3" },
      { label: "GBP Views/Month", value: "12,000+" },
      { label: "Organic Calls", value: "250+/mo" },
    ],
    badge: "HVAC",
    badgeColor: "green",
  },
  {
    id: "quickfix-roofing",
    company: "QuickFix Roofing Co.",
    industry: "Roofing",
    location: "Calgary, Canada",
    services: ["Web Design", "Local SEO"],
    resultHeadline: "4x Lead Increase",
    description: "New high-converting website with full Local SEO strategy for a roofing company in Calgary. Leads quadrupled in 5 months, making it one of the top-rated roofers in the city.",
    duration: "5 Months",
    metrics: [
      { label: "Lead Increase", value: "4x" },
      { label: "Website Traffic", value: "+220%" },
      { label: "Google Rating", value: "4.9★" },
      { label: "Page Speed Score", value: "94" },
    ],
    badge: "Roofing",
    badgeColor: "purple",
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    name: "Starter",
    price: "$300",
    period: "/month",
    description: "Perfect for small home service businesses getting started with digital marketing",
    features: [
      "Local SEO optimization",
      "Google Business Profile setup & optimization",
      "Basic website audit & fixes",
      "Monthly ranking report",
      "Review management strategy",
      "Email support",
    ],
    popular: false,
    ctaText: "Get Started",
  },
  {
    name: "Professional",
    price: "$600",
    period: "/month",
    description: "Full digital marketing package for growing home service businesses",
    features: [
      "Everything in Starter",
      "Google Ads management",
      "Meta Ads campaigns",
      "Conversion tracking & analytics",
      "Bi-weekly strategy calls",
      "Priority support & communication",
    ],
    popular: true,
    ctaText: "Get Started",
  },
  {
    name: "Enterprise",
    price: "$1,000",
    period: "/month",
    description: "End-to-end digital marketing for established home service businesses",
    features: [
      "Everything in Professional",
      "Custom web design",
      "Advanced technical SEO",
      "Priority support & communication",
      "Full marketing automation",
      "Weekly strategy calls",
    ],
    popular: false,
    ctaText: "Get Started",
  },
];

export const HOW_IT_WORKS = [
  {
    step: "01",
    title: "Discovery & Audit",
    description: "Deep dive into your business, competitors, and local market using AI analytics tools and proven research methods.",
    icon: "Search",
  },
  {
    step: "02",
    title: "Strategic Planning",
    description: "Build a custom Local SEO + paid ads strategy specific to your city, service area, and target customer.",
    icon: "Map",
  },
  {
    step: "03",
    title: "Implementation",
    description: "Execute the strategy using proven tools, GBP optimization, ad campaigns, and content with continuous monitoring.",
    icon: "Zap",
  },
  {
    step: "04",
    title: "Growth & Optimization",
    description: "Continuously optimize using real data, call tracking, and performance analytics for sustained lead growth.",
    icon: "TrendingUp",
  },
];

export const WHY_CHOOSE_ME = [
  {
    title: "Local SEO Mastery",
    description: "Deep expertise in Google Maps, GBP, and local rankings for home service businesses. I know what makes the algorithm tick.",
    icon: "MapPin",
  },
  {
    title: "Proven Track Record",
    description: "30+ successful projects with 95% client retention and real measurable results you can verify.",
    icon: "Trophy",
  },
  {
    title: "Home Services Specialist",
    description: "I ONLY work with HVAC, plumbing, roofing, electrical, and similar businesses. I speak your language and know your market.",
    icon: "Home",
  },
  {
    title: "Google & Meta Ads Expert",
    description: "AI-optimized paid campaigns with $2-$5 cost per conversion, not $20-$50 like most generalist agencies.",
    icon: "Target",
  },
  {
    title: "Direct Communication",
    description: "You work directly with me, not a junior team member. Expert strategy and communication on every project.",
    icon: "MessageCircle",
  },
  {
    title: "Full-Scope Solutions",
    description: "From Local SEO to paid ads to web design, I handle your entire digital marketing stack so you can focus on running your business.",
    icon: "Layers",
  },
];

export const INDUSTRIES = [
  {
    title: "HVAC Companies",
    description: "Heating, cooling, and air conditioning companies looking to dominate local search and get more service calls year-round.",
    example: "AirMax HVAC — 180%+ traffic growth",
    icon: "Wind",
    color: "from-blue-500 to-cyan-500",
  },
  {
    title: "Plumbing Services",
    description: "Plumbers and plumbing companies expanding their local market reach through Google Maps and targeted Google Ads.",
    example: "ProFlow Plumbing — 400+ monthly calls",
    icon: "Droplets",
    color: "from-purple-500 to-blue-500",
  },
  {
    title: "Roofing & Construction",
    description: "Roofers, contractors, and construction companies seeking more qualified project leads through local SEO and web design.",
    example: "QuickFix Roofing — 4x lead increase",
    icon: "Home",
    color: "from-violet-500 to-purple-500",
  },
];

export const TOOLS = {
  "SEO & Local Tools": [
    "Google Business Profile",
    "BrightLocal",
    "Whitespark",
    "Moz Local",
    "Ahrefs",
    "SEMrush",
    "Screaming Frog",
  ],
  "Google Ads Tools": [
    "Google Ads",
    "Performance Max",
    "Google Analytics 4",
    "Google Search Console",
    "Google Tag Manager",
  ],
  "Automation & AI": [
    "ChatGPT (GPT-4)",
    "Claude (Anthropic)",
    "Zapier",
    "Make.com",
    "n8n",
  ],
  "Design & Web": [
    "WordPress",
    "Elementor",
    "Figma",
    "PageSpeed Insights",
    "GTmetrix",
  ],
};

export const FAQ_ITEMS = [
  {
    q: "How long does it take to see results from Local SEO?",
    a: "Most clients start seeing improvements in Google Maps rankings within 60-90 days. Significant lead increases typically happen by month 3-4. Local SEO is a long-term investment that compounds over time — the longer you do it, the stronger your rankings become.",
  },
  {
    q: "Do you only work with home service businesses?",
    a: "My primary focus is HVAC, plumbing, roofing, electrical, and similar home service businesses in USA and Canada. This specialization means I understand your business deeply and know exactly what marketing strategies work for your industry.",
  },
  {
    q: "What makes your Google Ads different from other agencies?",
    a: "I specialize in home service Google Ads with a focus on call-only campaigns, Performance Max, and smart bidding strategies that consistently achieve $2-$5 cost per conversion — far below the industry average of $20-$50. I've optimized specifically for home service buyers.",
  },
  {
    q: "Do you offer a free consultation?",
    a: "Yes! I offer a free 30-minute consultation where I audit your Google Business Profile, check your local rankings, and give you a clear action plan. No obligation, just real value and honest feedback about your current digital marketing situation.",
  },
  {
    q: "Can you help businesses in any US or Canadian city?",
    a: "Yes, I work remotely with home service businesses across all major US and Canadian cities including Houston, Phoenix, San Antonio, Jacksonville, Columbus, Charlotte, Calgary, Edmonton, Ottawa, and more. Location is no barrier to results.",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "local-seo-for-hvac-companies",
    title: "Local SEO for HVAC Companies: The Complete Guide to Getting More Calls in 2026",
    excerpt: "Learn how HVAC companies can use Local SEO to rank #1 on Google Maps, get more calls, and dominate local search in USA and Canada. A complete 2026 strategy guide.",
    date: "2026-01-15",
    author: "Muhammad Umair",
    category: "Local SEO",
    readTime: "8 min read",
    metaDescription: "Learn how HVAC companies can use Local SEO to rank #1 on Google Maps, get more calls, and dominate local search in USA and Canada.",
    image: "https://www.mumairdigital.com/blog/hvac-local-seo-guide.jpg",
    keywords: ["Local SEO for HVAC", "HVAC Google Maps ranking", "HVAC lead generation", "home service SEO", "Google Business Profile HVAC"],
  },
  {
    slug: "google-business-profile-optimization-home-service-businesses",
    title: "Google Business Profile Optimization for Home Service Businesses: The Complete 2026 Guide",
    excerpt: "A step-by-step guide to optimizing your Google Business Profile so plumbers, roofers, electricians, and HVAC companies rank in the Google Maps 3-pack and get more calls.",
    date: "2026-03-10",
    author: "Muhammad Umair",
    category: "Google Business Profile",
    readTime: "10 min read",
    metaDescription: "Learn how to fully optimize your Google Business Profile in 2026 so your home service business ranks in the Maps 3-pack and gets more calls from Google.",
    image: "https://www.mumairdigital.com/blog/gbp-optimization-guide.jpg",
    keywords: ["Google Business Profile optimization", "GBP for home service businesses", "Google Maps 3-pack", "local SEO 2026", "plumber HVAC roofing GBP"],
  },
  {
    slug: "local-seo-for-plumbers-get-more-calls",
    title: "Local SEO for Plumbers: How to Get More Calls from Google in 2026",
    excerpt: "The complete Local SEO guide for plumbing companies. Learn how to rank #1 on Google Maps, dominate emergency plumbing searches, and fill your schedule with qualified leads.",
    date: "2026-04-05",
    author: "Muhammad Umair",
    category: "Local SEO",
    readTime: "9 min read",
    metaDescription: "Complete Local SEO guide for plumbers in 2026. Rank #1 on Google Maps, win emergency plumbing searches, and get more calls with proven strategies.",
    image: "https://www.mumairdigital.com/blog/local-seo-for-plumbers.jpg",
    keywords: ["local SEO for plumbers", "plumber Google Maps ranking", "how to get more plumbing leads", "plumbing SEO 2026", "Google Business Profile for plumbers"],
  },
  {
    slug: "google-ads-for-roofing-companies",
    title: "Google Ads for Roofing Companies: The Complete 2026 Guide to Getting More Jobs",
    excerpt: "A step-by-step Google Ads guide for roofing contractors. Learn campaign structure, storm damage keywords, bidding strategy, and how to get a 5-10x return on your ad spend.",
    date: "2026-04-16",
    author: "Muhammad Umair",
    category: "Google Ads",
    readTime: "11 min read",
    metaDescription: "Complete Google Ads guide for roofing companies 2026. Campaign structure, storm damage keywords, bidding strategy, and landing pages that convert visitors to jobs.",
    image: "https://www.mumairdigital.com/blog/google-ads-roofing-companies.jpg",
    keywords: ["Google Ads for roofing companies", "roofing PPC", "roofing Google Ads", "storm damage roofing ads", "roofing contractor marketing 2026"],
  },
];

export const LOCATIONS: Location[] = [
  {
    slug: "houston-tx",
    name: "Houston",
    state: "Texas",
    country: "United States",
    countryCode: "USA",
    population: "2.3 million",
    tagline: "Dominate Houston's Competitive Home Service Market",
    heroDescription: "Houston is one of the largest and most competitive home service markets in the USA. With extreme heat and humidity driving year-round HVAC demand and one of the fastest-growing populations in the country, Houston home service businesses need expert Local SEO to stand out.",
    marketFocus: "HVAC, plumbing, roofing, and electrical services",
    localStats: {
      businesses: "40,000+ home service businesses",
      homeServices: "High demand for HVAC, plumbing, and roofing",
    },
    testimonial: {
      author: "Carlos Rivera",
      company: "Texas Star Plumbing",
      role: "Owner",
      text: "Muhammad helped us dominate the Houston plumbing market. We went from page 3 to the top 3 on Google Maps in 4 months. Our phone rings constantly now.",
      result: "Top 3 Google Maps in Houston",
    },
    faqs: [
      { q: "How competitive is local SEO in Houston?", a: "Houston is highly competitive with thousands of home service businesses. That's why having an expert matters — I know how to get you to the top even in tough markets." },
      { q: "Which Houston neighborhoods do you target?", a: "I target all major Houston areas including The Woodlands, Sugar Land, Katy, Pearland, and all inner-loop neighborhoods based on where your customers are." },
      { q: "Do you work with Houston HVAC companies?", a: "Yes, HVAC is one of the highest-demand services in Houston due to the extreme heat. I have proven results with HVAC companies in the Houston metro area." },
    ],
    nearbyCities: [
      { name: "San Antonio, TX", slug: "san-antonio-tx" },
      { name: "Jacksonville, FL", slug: "jacksonville-fl" },
    ],
    schema: {
      addressLocality: "Houston",
      addressRegion: "TX",
      postalCode: "77001",
      addressCountry: "US",
      areaServed: "Greater Houston Area",
    },
  },
  {
    slug: "phoenix-az",
    name: "Phoenix",
    state: "Arizona",
    country: "United States",
    countryCode: "USA",
    population: "1.6 million",
    tagline: "Get More Home Service Leads in Phoenix & Scottsdale",
    heroDescription: "Phoenix is the 5th largest city in America with scorching summers that create massive demand for HVAC services. The Valley of the Sun's booming population makes it one of the best markets for home service businesses — if they can be found online.",
    marketFocus: "HVAC, roofing, plumbing, and pool services",
    localStats: {
      businesses: "25,000+ home service businesses",
      homeServices: "Extreme demand for HVAC due to 110°F+ summers",
    },
    testimonial: {
      author: "Mike Johnson",
      company: "Desert Cool HVAC",
      role: "Owner",
      text: "Phoenix summers mean everyone needs AC. Muhammad's Local SEO put us at the top of Google Maps right when demand spikes. Our revenue doubled year over year.",
      result: "Revenue doubled in 12 months",
    },
    faqs: [
      { q: "Is Phoenix a good market for HVAC SEO?", a: "Phoenix is one of the best HVAC markets in the country. With summers hitting 115°F, air conditioning is essential and demand is year-round." },
      { q: "Do you cover Scottsdale, Tempe, and Mesa?", a: "Yes, I optimize for the entire Phoenix metro area including Scottsdale, Tempe, Mesa, Chandler, Gilbert, and Peoria." },
      { q: "How fast can I rank in Phoenix?", a: "Phoenix is competitive but winnable. Most clients see meaningful ranking improvements within 3-4 months of starting." },
    ],
    nearbyCities: [
      { name: "Houston, TX", slug: "houston-tx" },
      { name: "San Antonio, TX", slug: "san-antonio-tx" },
    ],
    schema: {
      addressLocality: "Phoenix",
      addressRegion: "AZ",
      postalCode: "85001",
      addressCountry: "US",
      areaServed: "Greater Phoenix Metro Area",
    },
  },
  {
    slug: "san-antonio-tx",
    name: "San Antonio",
    state: "Texas",
    country: "United States",
    countryCode: "USA",
    population: "1.4 million",
    tagline: "Grow Your Home Service Business in San Antonio",
    heroDescription: "San Antonio is one of the fastest-growing cities in Texas with a strong military community, year-round warm weather, and high demand for HVAC, plumbing, and roofing services. Smart Local SEO can put your business at the top when San Antonio residents search for help.",
    marketFocus: "HVAC, plumbing, roofing, and electrical services",
    localStats: {
      businesses: "22,000+ home service businesses",
      homeServices: "Year-round demand driven by hot climate and growing population",
    },
    testimonial: {
      author: "John Martinez",
      company: "Alamo Roofing Services",
      role: "Owner",
      text: "Muhammad's Local SEO strategy transformed our San Antonio roofing business. We now rank #1 for roofing near me and get 50+ calls per month from Google alone.",
      result: "#1 Ranking for 'Roofing Near Me'",
    },
    faqs: [
      { q: "Can you rank my business in San Antonio?", a: "Yes, I have experience helping home service businesses in San Antonio rank on Google Maps and organic search." },
      { q: "Which areas of San Antonio do you target?", a: "I target all San Antonio areas including the North Side, South Side, Stone Oak, Alamo Ranch, Medical Center, and surrounding areas." },
      { q: "How does San Antonio compare to Houston for SEO?", a: "San Antonio is slightly less competitive than Houston, meaning results can often be achieved faster. Both are excellent markets for home service businesses." },
    ],
    nearbyCities: [
      { name: "Houston, TX", slug: "houston-tx" },
      { name: "Charlotte, NC", slug: "charlotte-nc" },
    ],
    schema: {
      addressLocality: "San Antonio",
      addressRegion: "TX",
      postalCode: "78201",
      addressCountry: "US",
      areaServed: "Greater San Antonio Area",
    },
  },
  {
    slug: "jacksonville-fl",
    name: "Jacksonville",
    state: "Florida",
    country: "United States",
    countryCode: "USA",
    population: "1.1 million",
    tagline: "Rank #1 in Jacksonville's Home Service Market",
    heroDescription: "Jacksonville is Florida's largest city by area with a humid subtropical climate that drives constant demand for HVAC, plumbing, and roofing services. As the city continues to grow rapidly, early investment in Local SEO means first-mover advantage.",
    marketFocus: "HVAC, plumbing, roofing, and lawn care",
    localStats: {
      businesses: "18,000+ home service businesses",
      homeServices: "Year-round demand for HVAC and storm damage roofing",
    },
    testimonial: {
      author: "Bob Williams",
      company: "JaxCool HVAC Services",
      role: "Owner",
      text: "Muhammad put us on the map — literally. We now appear in the Google Maps 3-pack for all major Jacksonville HVAC searches. Our call volume tripled in 6 months.",
      result: "Call volume tripled in 6 months",
    },
    faqs: [
      { q: "Is Jacksonville a growing market?", a: "Yes, Jacksonville is one of the fastest-growing metros in Florida, meaning more homeowners and more demand for home services every year." },
      { q: "Do you cover Jacksonville Beach and surrounding areas?", a: "Yes, I optimize for all Jacksonville zip codes including Jacksonville Beach, Ponte Vedra, Orange Park, and Mandarin." },
      { q: "What's the biggest opportunity in Jacksonville?", a: "HVAC is huge due to the Florida heat. If you're an HVAC company, Jacksonville Local SEO has an enormous ROI." },
    ],
    nearbyCities: [
      { name: "Charlotte, NC", slug: "charlotte-nc" },
      { name: "Columbus, OH", slug: "columbus-oh" },
    ],
    schema: {
      addressLocality: "Jacksonville",
      addressRegion: "FL",
      postalCode: "32099",
      addressCountry: "US",
      areaServed: "Greater Jacksonville Area",
    },
  },
  {
    slug: "columbus-oh",
    name: "Columbus",
    state: "Ohio",
    country: "United States",
    countryCode: "USA",
    population: "905,000",
    tagline: "Dominate Columbus Home Service Search Results",
    heroDescription: "Columbus is the fastest-growing city in the Midwest with a diverse economy and four-season climate that drives consistent demand for HVAC, plumbing, roofing, and electrical services. The city's large student population and growing suburbs create ideal conditions for home service businesses.",
    marketFocus: "HVAC, plumbing, roofing, and electrical services",
    localStats: {
      businesses: "15,000+ home service businesses",
      homeServices: "Four-season climate drives year-round demand",
    },
    testimonial: {
      author: "Sarah Anderson",
      company: "Buckeye Plumbing & Drain",
      role: "Owner",
      text: "Muhammad's SEO work made Columbus Plumbing our most visible competitor. We rank for dozens of local keywords and get consistent leads from Google every week.",
      result: "Ranking for 50+ local keywords",
    },
    faqs: [
      { q: "How competitive is Columbus for home service SEO?", a: "Columbus is moderately competitive and very achievable. Most clients see strong results within 3-4 months." },
      { q: "Which Columbus suburbs do you target?", a: "I target all Columbus areas including Dublin, Westerville, Gahanna, Grove City, Hilliard, and New Albany." },
      { q: "Is Columbus a good market for plumbing SEO?", a: "Absolutely. Columbus has an aging housing stock which means constant plumbing demand. It's a great market for plumbers investing in Local SEO." },
    ],
    nearbyCities: [
      { name: "Charlotte, NC", slug: "charlotte-nc" },
      { name: "Jacksonville, FL", slug: "jacksonville-fl" },
    ],
    schema: {
      addressLocality: "Columbus",
      addressRegion: "OH",
      postalCode: "43085",
      addressCountry: "US",
      areaServed: "Greater Columbus Metropolitan Area",
    },
  },
  {
    slug: "charlotte-nc",
    name: "Charlotte",
    state: "North Carolina",
    country: "United States",
    countryCode: "USA",
    population: "900,000",
    tagline: "Grow Your Charlotte Home Service Business With Local SEO",
    heroDescription: "Charlotte is one of the South's fastest-growing cities with a booming construction industry and hot, humid summers. As more residents move into new homes across the Charlotte metro, the demand for HVAC, plumbing, electrical, and roofing services is at an all-time high.",
    marketFocus: "HVAC, electrical, roofing, and new construction services",
    localStats: {
      businesses: "16,000+ home service businesses",
      homeServices: "Rapid population growth driving strong new construction demand",
    },
    testimonial: {
      author: "Tom Davis",
      company: "Carolina Electric Solutions",
      role: "Owner",
      text: "Muhammad's Local SEO has been a game-changer for our Charlotte electrical business. We now appear in the top 3 for electrical near me and our schedule is fully booked.",
      result: "Fully booked schedule from Google leads",
    },
    faqs: [
      { q: "Is Charlotte growing fast for home services?", a: "Charlotte is one of the fastest-growing cities in the Southeast. More people moving in means more homes needing services." },
      { q: "Which Charlotte areas do you optimize for?", a: "I target all of Charlotte including Ballantyne, SouthPark, Uptown, Concord, Gastonia, and Huntersville." },
      { q: "What services are most in demand in Charlotte?", a: "HVAC and electrical are extremely competitive and lucrative in Charlotte due to the hot summers and new construction boom." },
    ],
    nearbyCities: [
      { name: "Columbus, OH", slug: "columbus-oh" },
      { name: "Jacksonville, FL", slug: "jacksonville-fl" },
    ],
    schema: {
      addressLocality: "Charlotte",
      addressRegion: "NC",
      postalCode: "28201",
      addressCountry: "US",
      areaServed: "Greater Charlotte Metropolitan Area",
    },
  },
  {
    slug: "calgary-ab",
    name: "Calgary",
    state: "Alberta",
    country: "Canada",
    countryCode: "Canada",
    population: "1.3 million",
    tagline: "Calgary's Local SEO Expert for Home Service Businesses",
    heroDescription: "Calgary is Western Canada's business capital with extreme winters creating massive demand for furnace, heating, and HVAC services. As Canada's most entrepreneurial city, Calgary home service businesses that master local SEO gain a significant competitive advantage.",
    marketFocus: "HVAC, furnace repair, roofing, and plumbing",
    localStats: {
      businesses: "20,000+ home service businesses",
      homeServices: "Extreme winters drive high furnace and heating demand",
    },
    testimonial: {
      author: "David Thompson",
      company: "QuickFix Roofing Co.",
      role: "Owner",
      text: "Muhammad built us a new website and did complete Local SEO. Our leads quadrupled in 5 months. Best investment we made for our Calgary roofing business.",
      result: "4x Lead Increase in 5 Months",
    },
    faqs: [
      { q: "Do you understand the Canadian market?", a: "Yes, I work with businesses across Canada including Calgary, Edmonton, and Ottawa. I understand Canadian search behavior and the local home service market." },
      { q: "Which Calgary neighborhoods do you target?", a: "I target all Calgary communities including NW, NE, SW, SE Calgary, and surrounding towns like Airdrie, Cochrane, and Chestermere." },
      { q: "Is Calgary furnace and HVAC SEO competitive?", a: "Very competitive but very lucrative. Calgary winters make HVAC essential. I've helped HVAC companies break into the top 3 in Calgary." },
    ],
    nearbyCities: [
      { name: "Edmonton, AB", slug: "edmonton-ab" },
      { name: "Ottawa, ON", slug: "ottawa-on" },
    ],
    schema: {
      addressLocality: "Calgary",
      addressRegion: "AB",
      postalCode: "T2P 1J9",
      addressCountry: "CA",
      areaServed: "Greater Calgary Area",
    },
  },
  {
    slug: "edmonton-ab",
    name: "Edmonton",
    state: "Alberta",
    country: "Canada",
    countryCode: "Canada",
    population: "1.0 million",
    tagline: "Rank #1 in Edmonton for Home Service Searches",
    heroDescription: "Edmonton is Alberta's capital and has Canada's most extreme winters, creating enormous demand for furnace repair, HVAC, and insulation services. As Edmonton's economy diversifies and grows, home service businesses have a golden opportunity to capture market share through smart local SEO.",
    marketFocus: "HVAC, furnace repair, insulation, and roofing",
    localStats: {
      businesses: "16,000+ home service businesses",
      homeServices: "Canada's coldest winters create extreme furnace and heating demand",
    },
    testimonial: {
      author: "Lisa Park",
      company: "Edmonton Furnace Pros",
      role: "Owner",
      text: "Working with Muhammad was the best decision for our Edmonton business. He got us into the top 3 for furnace repair Edmonton before our busiest winter season. Revenue increased by 65%.",
      result: "65% Revenue Increase in First Winter",
    },
    faqs: [
      { q: "What are the biggest opportunities for SEO in Edmonton?", a: "Furnace and heating services are massive in Edmonton. With temperatures dropping to -40°C, everyone needs a working furnace and will pay for emergency service." },
      { q: "Do you cover Edmonton suburbs?", a: "Yes, I target all of Edmonton including St. Albert, Sherwood Park, Spruce Grove, Leduc, and Fort Saskatchewan." },
      { q: "How is Edmonton SEO different from Calgary?", a: "Edmonton is slightly less competitive than Calgary, making it easier to rank. Both cities have strong demand for heating and HVAC services." },
    ],
    nearbyCities: [
      { name: "Calgary, AB", slug: "calgary-ab" },
      { name: "Ottawa, ON", slug: "ottawa-on" },
    ],
    schema: {
      addressLocality: "Edmonton",
      addressRegion: "AB",
      postalCode: "T5J 0N3",
      addressCountry: "CA",
      areaServed: "Greater Edmonton Area",
    },
  },
  {
    slug: "ottawa-on",
    name: "Ottawa",
    state: "Ontario",
    country: "Canada",
    countryCode: "Canada",
    population: "1.0 million",
    tagline: "Ottawa Local SEO Expert for Home Service Businesses",
    heroDescription: "Ottawa is Canada's capital and a stable, government-driven economy that keeps the housing market strong year-round. Harsh winters create consistent demand for HVAC, furnace, and plumbing services, while summer brings roofing and AC demand. Ottawa home service businesses can thrive with the right Local SEO strategy.",
    marketFocus: "HVAC, plumbing, roofing, and electrical services",
    localStats: {
      businesses: "14,000+ home service businesses",
      homeServices: "Government city with stable housing market and consistent service demand",
    },
    testimonial: {
      author: "Pierre Leblanc",
      company: "Capital Plumbing Ottawa",
      role: "Owner",
      text: "Muhammad's Local SEO put Capital Plumbing on the map in Ottawa. We went from zero online presence to appearing in the top 3 within 5 months. Our business grew 80% in the first year.",
      result: "80% Business Growth in Year One",
    },
    faqs: [
      { q: "Do you work in both English and French markets in Ottawa?", a: "I focus primarily on English-language SEO, which covers the majority of Ottawa searches. For French-language SEO, I can discuss a bilingual strategy." },
      { q: "Which Ottawa areas do you target?", a: "I target all Ottawa areas including Kanata, Barrhaven, Orleans, Gloucester, Nepean, and Gatineau for businesses serving the NCR." },
      { q: "How does Ottawa compare to Toronto for SEO?", a: "Ottawa is far less competitive than Toronto, making it easier to rank and achieve results faster. It's a great market for home service businesses to invest in SEO." },
    ],
    nearbyCities: [
      { name: "Calgary, AB", slug: "calgary-ab" },
      { name: "Edmonton, AB", slug: "edmonton-ab" },
    ],
    schema: {
      addressLocality: "Ottawa",
      addressRegion: "ON",
      postalCode: "K1A 0A3",
      addressCountry: "CA",
      areaServed: "Ottawa-Gatineau Region",
    },
  },
];
